name: mshmobile
description: munshare mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dynamic_theme: ^1.0.1

  # 路由管理
  auto_route: ^0.4.4

  #状态管理
  provider: ^4.3.1

  #屏幕适配
  flutter_screenutil: ^2.3.0

  #toast
  fluttertoast: ^7.0.1

  # ui
  flutter_easyrefresh: ^2.1.0

  # http
  dio: ^3.0.9
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0

  # storage 本地缓存
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0

  # sha 加密函数
  crypto: ^2.1.3

  # html文件解析
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancloud_storage: ^0.2.9
  # 路由生成
  auto_route_generator: ^0.4.4
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/images/signup.jpg
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

